# Generated by Django 6.0.3 on 2026-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
